### ISSUE TITLE
Not a valid repository location

### ISSUE THREAD

**Issue by tinvyhxx** [GoClipse/goclipse#104]
Unable to read repository at http://goclipse.github.io/releases/.
Unable to read repository at http://goclipse.github.io/releases/.
http://goclipse.github.io/releases/ is not a valid repository location

For I am from China maybe , would you please put a offline zip download for eclipse plugins installing .

**Comment by bruno-medeiros** [comment]
Can you download: https://github.com/GoClipse/goclipse.github.io/archive/master.zip ?
If so, that should work: just unzip the file, and add the releases/ directory as an Eclipse local repository.

**Comment by bruno-medeiros** [comment]
Can you download: https://github.com/GoClipse/goclipse.github.io/archive/master.zip ?
If that URL is not blocked in China, then it should work: just unzip the file, and add the releases/ directory as an Eclipse local repository.

**Comment by tonystz** [comment]
I encounter the same issue and download the said master.zip, but why I cannot import it? could you say more? Thanks.

**Comment by bruno-medeiros** [comment]
Did you press "Local..." in the add repository dialog, and select the releases/ directory? :
![local_repo](https://cloud.githubusercontent.com/assets/4324232/5738914/255a2918-9bea-11e4-99b9-fbbc4f51dd43.png)

**Comment by tonystz** [comment]
I did as your said, but the error below appeared.
![image](https://cloud.githubusercontent.com/assets/8477911/5750760/0dffa4d2-9c94-11e4-845d-24b9cc791405.png)

Here is my eclipse version:
![image](https://cloud.githubusercontent.com/assets/8477911/5750774/4802760a-9c94-11e4-906a-aac3088a547c.png)

Thanks for your helps in advance!

**Comment by bruno-medeiros** [comment]
Hum, that's quite odd. Can you attach the Eclipse Error Log (`"Help/About/Installation Details/Configuration/Error Log"`), so I can try to figure out what's wrong?

**Comment by bruno-medeiros** [comment]
will reopen if there is more info

**Comment by Ostrolutskiy** [comment]
I've faced the same problem.
You should include the folder 'local-repo' too.
Hope it will solve problem :)

.../goclipse.github.io-master/releases/**local-repo/**
