### ISSUE TITLE
Project Explorer does not expand GOROOT for Go 1.4

### ISSUE THREAD

**Issue by secmask** [GoClipse/goclipse#105]
Hi
I am using eclipse 4.4 with goclipse 0.91, with go 1.3 everything is fine
but after I switch to go 1.4, goclipse cannot expand GOROOT in the treeview(just as an empty node), no error message, no error log line.
I wish it could be fix.
Thanks

**Comment by bruno-medeiros** [comment]
I've confirmed this bug. Seems that in 1.4 they changed the package directory layout a bit, and moved the contents of <go>/src/pkg to <go>/src/. As a temporary workaround, you can create the <go>/src/pkg directory, and copy the contents of <go>/src/ to it.

**Comment by secmask** [comment]
yep, I've made a symbolink for it and it's fine now :+1:  thank you.
