### ISSUE TITLE
Get full listing of all compiler errors

### ISSUE THREAD

**Issue by echaz** [GoClipse/goclipse#106]
The Go compiler typically quits after 10 compiler errors.  It would be nice to enable all of them.

from https://golang.org/cmd/gc/

It looks like adding a -e should pull out other compiler errors from the go compiler.

**Comment by bruno-medeiros** [comment]
Thanks for bringing that up, I wasn't aware of that behavior and option. However it seems the limit of 10 compiler errors is per package, not per build, so the default behavior seems reasonable to me. Users can add "-e" to the extra build options gcflags if they so desire.

**Comment by echaz** [comment]
thanks for directing me how to override this behavior!
