### ISSUE TITLE
org.json can not found when i import the whole project into eclipse sdk 4.4

### ISSUE THREAD

**Issue by liugangnhm** [GoClipse/goclipse#107]
org.json can not found when i import the whole project into eclipse sdk 4.4, what exactly is the 'org.json ' lib ?

**Comment by bruno-medeiros** [comment]
"Setup the target platform: Open the target platform file: `releng/target-platform/IDE.target` and set it as your target platform." -> https://github.com/GoClipse/goclipse#setting-up-the-development-environment
