### ISSUE TITLE
Error markers for test files

### ISSUE THREAD

**Issue by baconalot** [GoClipse/goclipse#108]
Currently test files "XYZ_test.go" do not generate error markers in eclipse. It would be handy if they did.

**Comment by bruno-medeiros** [comment]
Indeed it would be handy. The toolchain doesn't seem to make it trivial to perform that though: https://groups.google.com/forum/#!topic/golang-nuts/Nh987sln3wA

**Comment by snuk182** [comment]
what I do now is renaming *_test.go into *_testo.go (i.e. something that breaks Go's testfiles detection). often forgetting to rename it back though :( mb some kind of automated renaming during build can be done?
