### ISSUE TITLE
can't create a go project

### ISSUE THREAD

**Issue by mwaaas** [GoClipse/goclipse#109]
This is the error am getting 

Errors occurred during the build.
Errors running builder 'Go Project Builder' on project 'Helloworld'.
Go Environment settings are not valid
Go Environment settings are not valid

which settings are this 

am a begginer  in go from python world

**Comment by bruno-medeiros** [comment]
You need to configure Go environment settings in `Preferences / Go `. There's more info in the Goclipse user guide:
https://github.com/GoClipse/goclipse/blob/latest/documentation/UserGuide.md#goclipse-prerequisites-and-initial-setup
Note, before anything else, you will need to be familiar on how to organize your Go code in a way that the Go toolchain understands, so, if you haven't already, you'll need to read this Go workspace guide: http://golang.org/doc/code.html
