### ISSUE TITLE
Project Properties -> Go Build Path : No Options Working

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#11]
Reported by davidpfarrell, Oct 24, 2011
What steps will reproduce the problem?
1. Right Click on a GoClipse project
2. Select "Properties"
3. Select "Go Build Path"

What is the expected output? What do you see instead?

None of the "add" options are working in any of the Source, Projects, or Libraries tabs.

Clicking "Add Folder" in source tab brings up an empty window saying "No entries available"

Clicking "Add" in Projects or Libraries tab does nothing.

What version of the product are you using? On what operating system?

Using GoClipse 0.2.1 on Helios Service Release 2 on Mac OSX Lion.

**Comment by bruno-medeiros** [comment]
invalid
