### ISSUE TITLE
It appears goclipse doesn't work with Luna (4.4.2)

### ISSUE THREAD

**Issue by seterryxu** [GoClipse/goclipse#115]
It appears goclipse doesn't work with Luna (4.4.2). I don't know if others have encountered the same problem.

**Comment by bruno-medeiros** [comment]
What problems are you having? I've just tried Goclipse with 4.4.2, and it seems to be working fine.

**Comment by LindsayBradford** [comment]
I have a working goclipse 0.91 under Eclipse Luna.

**Comment by bruno-medeiros** [comment]
seems invalid, reopen if you have more details.

**Comment by seterryxu** [comment]
Sorry to trouble u. Problems still exists. Perhaps it's because I didn't
install it properly.
What's the correct installation method by using eclipse "Install New
Software"?

**Comment by bruno-medeiros** [comment]
The installation instructions are detailed here: https://github.com/GoClipse/goclipse/blob/master/documentation/Installation.md . If that failed, I'm going to need more info: the Eclipse Error Log, and the Configuration Log (see here: https://github.com/GoClipse/goclipse/blob/master/CONTRIBUTING.md#reporting-issues)

**Comment by seterryxu** [comment]
Thanks very much for u r great help! I finally solved the problems. It's
because of the GFW(Great Firewall) in China which blocks network transfer
and  the update process. It's really very boring. Thanks a lot!
And I'd suggest u publish Goclipse to Eclipse Marketplace, which may help
developers to install it more easily.

Best regards.

**Comment by bruno-medeiros** [comment]
Ahh, I had forgotten about this problem actually: I've had users complain about it before. I've added this info to the Installation guide:
https://github.com/GoClipse/goclipse/blob/latest/documentation/Installation.md#note-for-users-in-china

**Comment by bruno-medeiros** [comment]
Ahh, I had forgotten about this problem actually: I've had users complain about it before. I've added this info to the Installation guide:
https://github.com/GoClipse/goclipse/blob/latest/documentation/Installation.md#cn-note-for-users-in-china
