### ISSUE TITLE
Error marker after go build not show

### ISSUE THREAD

**Issue by secmask** [GoClipse/goclipse#116]
In goclipse 0.91, if there any error (syntax, invalid expression...) with go build, it will show in editor with marker, that's useful. But I don't see this feature in 0.10 release? How can I take it back?

**Comment by bruno-medeiros** [comment]
You need to add `./...` to the "Arguments for go build" in the project properties. Open the project context menu, select `Project / Go Project Configuration`

**Comment by secmask** [comment]
My project has already have this `-gcflags "-N -l" ./...` in that section, but it did not work.

**Comment by bruno-medeiros** [comment]
What's the output of the Go build console?

**Comment by secmask** [comment]
This is it
```
-------   Building Go project: gogo  -------
>> Running: /devel/tools/go/bin/go install -v -gcflags -N -l ./...
   with GOPATH: /devel/workspace/gogo:/devel/workspace/goprojects:/devel/workspace/gomy
github.com/secmask
# github.com/secmask
src/github.com/secmask/gmain.go:140: use of package log without selector
   ^^^ Terminated, exit code: 2 ^^^
```

**Comment by markose** [comment]
I can confirm this. Same behaviour with my installation:
Goclipse 0.10
Eclipse 4.4.1 (Build: 20140925-1800)
