### ISSUE TITLE
Incorrect highlight for single-quoted single quote

### ISSUE THREAD

**Issue by CarlSmotricz** [GoClipse/goclipse#117]
* GoClipse: 0.10.0
* OS: Windows 7 64 bit
* Arch: Intel I5-3550

To reproduce, copy/paste and view these 2 lines of valid Go code in the editor:

const qa = '\a' // The "alarm" character as a rune
const qq = '\'' // A single quote as a rune

![image](https://cloud.githubusercontent.com/assets/11720421/6897498/711abc60-d6f4-11e4-9db0-daa55d489b63.png)

* The 1st line shows the character constant in blue and the comment in green (OK)
* The 2nd line shows the comment in blue (doesn't realize the string has ended) (bad)

**Comment by bruno-medeiros** [comment]
fixed

**Comment by CarlSmotricz** [comment]
Woo hoo! Thanks for the really quick fix! :)
