### ISSUE TITLE
"Stop" button disappears when making a build while app is running

### ISSUE THREAD

**Issue by evgeniynickolaev** [GoClipse/goclipse#120]
Hello!

Consider an app is launched:

![image](https://cloud.githubusercontent.com/assets/305699/6962990/9b4c8194-d942-11e4-9cab-a87dc0e90342.png)

When I save a file so a rebuild process is launched, stop button dissapears:

![image](https://cloud.githubusercontent.com/assets/305699/6963026/e70a133a-d942-11e4-9763-247e5efc3c18.png)

And it appears only after the app outputs something (log entries are not being lost).

If an app outputs nothing or does it seldom, I have to terminate it using "Debug" perspective.

Thank you!

**Comment by bruno-medeiros** [comment]
This is not a bug: each console page in the Console view can supply different buttons. It just so happens that the console for a launch process provides the stop button, but the Go build console doesn't. Maybe this could be done as an enhancement though. Note that you can stop the build with the Progress view, there is a stop button there:
![untitled](https://cloud.githubusercontent.com/assets/4324232/6983497/88b70c46-da16-11e4-9f91-1f393ef4f4fe.png)

**Comment by bruno-medeiros** [comment]
In other words, even when no app is running, there is still no stop button for the Go build

**Comment by bruno-medeiros** [comment]
Also, if it the app that you want to stop, you will need to change to the app console page in the Console view, then the stop button for the app will reappear

**Comment by evgeniynickolaev** [comment]
Got it, just my lack of Eclipse knowledge.
Thanks!
