### ISSUE TITLE
Oracle Open Definition not working for type references: "selected name does not refer to a source element"

### ISSUE THREAD

**Issue by baconalot** [GoClipse/goclipse#121]
From issue https://github.com/GoClipse/goclipse/issues/99

When a type is ctrl-clicked we get " selected name does not refer to a source element, rather its a ref to type xyz (size 40, align 8). Is there a compelling reason not to jump to the type? 

Given this program:
```
package main

import "fmt"

type Foo struct {
	A string
	B string
}

func main() {
	foo := Foo{"a", "b"}
	fmt.Println(foo)
}
```
When I ctrl-lmb click `foo` in `fmt.Println(foo)` it jumps to the definition of `foo` on the previous line -> ok
When I ctrl-lmb click `Foo` in `foo := Foo{"a", "b"}` I get the following message:
![untitled](https://cloud.githubusercontent.com/assets/1876368/6983073/eec13e96-da19-11e4-9b51-a3b8ea8bf974.png)
Since the position of the type is know anyway why not jump to it?

**Comment by baconalot** [comment]
In com.googlecode.goclipse.tooling -> src/com/googlecode/goclipse/tooling/oracle/GoOracleFindDefinitionOperation.java

	protected FindDefinitionResult parseJsonResult(String output) throws JSONException, CommonException {
		JSONObject jsonResult = new JSONObject(output);
		
		JSONObject describe = jsonResult.getJSONObject("describe");
		
		String desc = describe.getString("desc");
		
		if(areEqual(desc, "source file")) {
			return new FindDefinitionResult(null, null);
		}
		if(!areEqual(desc, "identifier")) {
			return new FindDefinitionResult(
				"Selected name does not refer to a source element, rather it's a:\n" + desc, null);
		}

**Comment by dave-leblanc-agora** [comment]
I'm wondering when we can expect this change to be in the releases? I updated my eclipse plugin and checked the manual download file from master and the latest release was compiled several days prior to this patch. I'm not familiar with your release schedule and apologize if this information is available elsewhere however this issue has been plaguing me for a little while now.

**Comment by bruno-medeiros** [comment]
I don't have a release schedule, as I work in many different projects, and it's hard to plan work for a single IDE. If there is a good amount of features in master, I usually do a release, unless I have short term plans to add more stuff.

You can see the upcoming feature in the changelog file:
https://github.com/GoClipse/goclipse/blob/master/documentation/ChangeLog.md

**Comment by dave-leblanc-agora** [comment]
ok thanks for the reply I'll keep an eye on things. Kudos to you for building this project!
