### ISSUE TITLE
need support for auto show the function's information 

### ISSUE THREAD

**Issue by jiangyubao** [GoClipse/goclipse#126]
for example, code shown as bellow:
package main
import "fmt"
function main(){
fmt.Println(
}

after type 'fmt.Println(',or press 'Alt+/', goclipse will show  the function's information.

**Comment by parhamdoustdar** [comment]
:plus1:

**Comment by wolfgangmeyers** [comment]
it would also be helpful to show the function or type documentation when hovering over it with a mouse in the editor.

**Comment by pulkitpivotal** [comment]
:+1:
