### ISSUE TITLE
double click project after eclipse start up , and it display an error message dialog

### ISSUE THREAD

**Issue by jiangyubao** [GoClipse/goclipse#127]
The error message is:
An error has occurred. See error log for more detail
 null argument

**Comment by bruno-medeiros** [comment]
So... what does the Error log say?? 
-> https://github.com/GoClipse/goclipse/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by jiangyubao** [comment]
it say:" null argument"

**Comment by jiangyubao** [comment]
![a](https://cloud.githubusercontent.com/assets/1122460/7269598/e08622cc-e907-11e4-8778-9d9044188c9c.jpg)

**Comment by bruno-medeiros** [comment]
No, I mean the Eclipse Error Log, it can be found in `Help/About/Installation Details/Configuration/Error Log`. There should be more info about the error there.

**Comment by bruno-medeiros** [comment]
Nevermind, I'm managed to replicate it in my machine.
