### ISSUE TITLE
Console doesn't support unicode

### ISSUE THREAD

**Issue by wushilin** [GoClipse/goclipse#128]
try this: fmt.Println("測試")

And the output is malformed.

**Comment by bruno-medeiros** [comment]
I just tried it and it seems to be working fine.
![untitled](https://cloud.githubusercontent.com/assets/4324232/7200484/65a2da02-e4f5-11e4-8dea-5dd175f136ae.png)

What encoding is the file being saved with? To check that, right click the file you are editing, and open `Properties`, then check the `Resource` tab to check the encoding.

**Comment by wushilin** [comment]
HI, it is UTF8. 

However, I figured out that at the project properties, there is a text-file encoding. I changed it from GBK to utf-8 and it worked. Can that be made as utf-8 by default?

Thanks for your useful suggestion though.

**Comment by bruno-medeiros** [comment]
Yes, open Preferences, and then under ` General / Workspace` there is a setting to control the default text encoding for the whole workspace.
