### ISSUE TITLE
Project with version control support?

### ISSUE THREAD

**Issue by secmask** [GoClipse/goclipse#129]
Do you have a plan to support version control (such as git)? GoClipse is so good IDE, but I cannot use version control (file changes indicator, push, pull ..) with go projects :(

**Comment by bruno-medeiros** [comment]
I guess you figured out you just need to install the Eclipse Git features :)

**Comment by secmask** [comment]
I always thing that a project should have a `src` folder in it (the very early day I begin with Go and GoClipse), GOPATH seem match, so I create my project on in. That organize quite good, I can work on everything and switch between subproject fast, and of course I cann't enable git for such big project. For now, I create a Go project from GOPATH's subtree directory(GOPATH/src/github.com/secmask/myproj), that's work good with git now :)
