### ISSUE TITLE
main package cann't build to project folder bin 

### ISSUE THREAD

**Issue by chinamerp** [GoClipse/goclipse#130]
the project cann't run because the main package build to GoRoot\bin

**Comment by z772458549** [comment]
I have the same problem.Run with GOPATH，but executable file build to GoRoot\bin not GOPATH\bin

**Comment by bruno-medeiros** [comment]
Sounds like you might have setup your Goclipse GOPATH/GOROOT settings incorrectly. What does is the output of the `Go build` console when your build your project?

**Comment by z772458549** [comment]
Thank you very much,some like compile source code has problems.I compile and build it again,no problem
