### ISSUE TITLE
Syntax Highlight Under Eclipse Dark Theme

### ISSUE THREAD

**Issue by windweller** [GoClipse/goclipse#131]
How can I automatically change the syntax highlighting (not manually) when the Eclipse theme is dark? Right now the highlighting is not synchronous with the theme...

**Comment by bruno-medeiros** [comment]
It's not synchronous with the theme ya. But is that a big issue? If you're using Dark theme, don't you use it all the time?

**Comment by russel** [comment]
Dark theme is the only way I use Eclipse. Currently (2015-08-30), GoClipse editor is using black on black in the editor, which comes under the heading of unfit for purpose. It seems manually adjusting all the editor colours is the only way of dealing with this. Thus I don't use GoClipse.

**Comment by mackenza** [comment]
@bruno-medeiros is it not possible for you to just let the syntax color elements pick up their defaults from Eclipse default? Most of the languages do that. Then you don't have to ever touch custom colors as people's UI themes will be fine.

**Comment by bruno-medeiros** [comment]
@mackenza I'm not sure what you mean there. With regards to the editor, there are only generic Eclipse defaults for text color, background color, etc., but not for language specific syntax elements (like keywords, string literals, comments, etc.). So there is nowhere to pick up these defaults from, the Go IDE has to provide them.
