### ISSUE TITLE
installation hangs on org.eclipse.ecf.provider.bittorrent.source

### ISSUE THREAD

**Issue by tzniuta** [GoClipse/goclipse#134]
hello. i installing goclipse to ecilpse mars but it stops at 

```
installing software
installing software: downloading org.eclipse.ecf.provider.bittrorrent.source
```
is there any idea why this happening? i know this may not be related to the goclipse but
what the use if this cannot be install. 

thank you.

**Comment by bruno-medeiros** [comment]
Are you living in China? If so, have you seen the installation section: https://github.com/GoClipse/goclipse/blob/latest/documentation/Installation.md#cn-note-for-users-in-china
