### ISSUE TITLE
Goclipse not detecting Java 8

### ISSUE THREAD

**Issue by peterjiz** [GoClipse/goclipse#136]
OS: OS X 10.10.3 
JDK Installed: 1.8.0_45 
Eclipse: 4.5 Mars 

On Eclipse launch, Goclipse errors out saying Java needs to be upgraded to version 8. 
Uninstalled Goclipse and re-installed, nothing

**Comment by bruno-medeiros** [comment]
Can you post your Configuration Log: This can be found at "Help/About/Installation Details/Configuration"

**Comment by nmabhinandan** [comment]
I'm having the same problem. This is my configuration log.

http://paste.ubuntu.com/12446647/

**Comment by bruno-medeiros** [comment]
> I'm having the same problem. This is my configuration log.
> 
> http://paste.ubuntu.com/12446647/

From the log it's clear that your Eclipse is being started with Java 7 ("java.version=1.7.0_79"). Note, it's not enough to merely have Java 8 installed, you also have to either:
* Have Java 8 be the default java (i.e., `java` on the PATH is the one for version 8. You can check with `java -version`)
* Alternatively, explicitly specify the Java VM that Eclipse uses, with the Eclipse `-vm` parameter. So for example: `eclipse -vm /usr/lib/jvm/java-8-openjdk-i386/bin/java`, or wherever Java 8 is installed

**Comment by Astelit** [comment]
Have same error on Windows 7 and Eclipse 4.5 Mars
Console shows Java version 1.8 as default one.
Any suggestion?

**Comment by bruno-medeiros** [comment]
@Astelit Open the Eclipse Configuration Log (see https://github.com/GoClipse/goclipse/blob/master/CONTRIBUTING.md ), what is the `java.home` property there?

**Comment by tweg** [comment]
@peterjiz you can edit the "Eclipse.app/Contents/Eclipse/eclipse.ini" , set the "-vm /usr/bin" or  or wherever Java 8 is installed.

**Comment by echarlus** [comment]
Same issue here on Max OS X 10.11.3. 
I have both JDK 1.7 and 1.8 installed. 
I've switched to 1.8 by setting JAVA_HOME to the 1.8 location. 
java -version gives 1.8 
I start eclipse from the same shell and despite that it's still complaining that it's using 1.7. 
Looking at the configuration as explained in above posts shows that it's using 1.7 ...
I've managed to make it work by invoking eclipse with -vm /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/server/libjvm.dylib
But I do not see why it's not picking up the correct version even when the local environment is setup correctly ...

**Comment by bruno-medeiros** [comment]
This seems to be a Mac OS X specific issue with regards to Eclipse in general (not Goclipse).  Unfortunately I'm completely unfamiliar with OS X, I only have Windows and Linux boxes. I did a quick google search and came up with this, maybe it's the same problem? :  http://stackoverflow.com/questions/14806709/application-is-using-java-6-from-apple-instead-of-java-7-from-oracle-on-mac-os-x

**Comment by echarlus** [comment]
Thanks for the answer. 
I found a cleaner way to start Eclipse with the correct VM. My previous method was causing problems (at least some graphical resources were not loaded properly). 
I edited the Info.plist file located in the Eclipse.app bundle and found a comment explaining how to select the runtime VM. 
Adding <string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java</string> in the .plist file did the trick and now everything seems to be fine. 
I still do not know why it's selecting 1.7 instead of 1.8 at startup by default ...

**Comment by bruno-medeiros** [comment]
> -vm /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/server/libjvm.dylib

Yeah, the above option looked very strange, I think -vm option is supposed to point to either the root folder of the jdk installation, or a java binary. Not sure what the above does.

BTW, take a look at the Mac OS X section here: http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Frunning_eclipse.htm . It mentions editing eclipse.ini in the Eclipse application bundle. Maybe there's an already an option there selecting a specific JVM, and that's what's causing the problem?

**Comment by echarlus** [comment]
yes, that's basically what I did by editing the Info.plist 
In the file itself there is a comment showing how to use an alternate VM.
Why I still do not understand is why it's using the 7.0 version by default, not taking into account the JAVA_HOME env variable ...

**Comment by bruno-medeiros** [comment]
I'm not sure if Eclipse even looks into JAVA_HOME, maybe only PATH. But if it does, are you sure Eclipse is picking up your JAVA_HOME in the first place? Mac OS X has some quirks where environment variables for the shell are not the same as for applications launched from the desktop. This has caused problems with GOROOT/GOPATH too, see: https://github.com/GoClipse/goclipse/issues/91#issuecomment-82494180
