### ISSUE TITLE
Content Assist and F3 does not work

### ISSUE THREAD

**Issue by huskercane** [GoClipse/goclipse#137]
I am using latest release

My project builds code properly.

When I press ctrl+space it does not work, F3 also does not work

```
====================  Starting gocode server:    ====================
   /usr/local/go/bin/gocode -s -sock=tcp
>> Running: /usr/local/go/bin/gocode -sock=tcp set lib-path /home/rohits/p1/p1trunk/psasmaster:/home/rohits/Desktop/gocode:/home/rohits/Work/vault
   with GOPATH: /home/rohits/p1/p1trunk/psasmaster:/home/rohits/Desktop/gocode:/home/rohits/Work/vault
lib-path "/home/rohits/p1/p1trunk/psasmaster:/home/rohits/Desktop/gocode:/home/rohits/Work/vault"
>> Running: /usr/local/go/bin/gocode -sock=tcp -f=csv autocomplete /psasmaster/src/xxx.com/xxx/messagehub/main.go c246
   with GOPATH: /home/rohits/ipas/ipastrunk/psas.mastermgmt:/home/rohits/Desktop/gocode:/home/rohits/Work/vault
panic: open /psasmaster/src/xxx.com/xxx/messagehub/main.go: no such file or directory
1(runtime.call16): /usr/local/go/src/runtime/asm_amd64.s:401
2(runtime.gopanic): /usr/local/go/src/runtime/panic.go:387
3(main.find_other_package_files): /home/rohits/Desktop/gocode/src/github.com/nsf/gocode/autocompletecontext.go:419
4(main.get_other_package_files): /home/rohits/Desktop/gocode/src/github.com/nsf/gocode/autocompletecontext.go:384
5(main.(*auto_complete_context).update_caches): /home/rohits/Desktop/gocode/src/github.com/nsf/gocode/autocompletecontext.go:159
6(main.(*auto_complete_context).apropos): /home/rohits/Desktop/gocode/src/github.com/nsf/gocode/autocompletecontext.go:252
7(main.server_auto_complete): /home/rohits/Desktop/gocode/src/github.com/nsf/gocode/server.go:155
8(main.(*RPC).RPC_auto_complete): /home/rohits/Desktop/gocode/src/github.com/nsf/gocode/rpc.go:26
9(runtime.call64): /usr/local/go/src/runtime/asm_amd64.s:403
10(reflect.Value.call): /usr/local/go/src/reflect/value.go:419
11(reflect.Value.Call): /usr/local/go/src/reflect/value.go:296
12(net/rpc.(*service).call): /usr/local/go/src/net/rpc/server.go:382
13(runtime.goexit): /usr/local/go/src/runtime/asm_amd64.s:2232

PANIC,,PANIC,,PANIC

```

it is correct /psasmaster/src/xxx.com/xxx/messagehub/main.go, is not a proper file

seems like plugin is only using  "/"<proect_name>/<path_to_file>.go as argument to gocode.

Should this be full path? or I have wrong project setup

my project setup is
<project name>
  src
    <xxx.com>
       dir
         dir
           file.go

**Comment by bruno-medeiros** [comment]
`/usr/local/go/bin/gocode -sock=tcp -f=csv autocomplete /psasmaster/src/xxx.com/xxx/messagehub/main.go c246` Yeah, this call, the go file should be absolute path. I don't see why it wouldn't work. Also, this is very strange:
``` 
   with GOPATH: /home/rohits/p1/p1trunk/psasmaster:/home/rohits/Desktop/gocode:/home/rohits/Work/vault
...
   with GOPATH: /home/rohits/ipas/ipastrunk/psas.mastermgmt:/home/rohits/Desktop/gocode:/home/rohits/Work/vault
``` 
These two calls should have the same value of GOPATH. Which GOPATH do you actually have set?

**Comment by bruno-medeiros** [comment]
`/usr/local/go/bin/gocode -sock=tcp -f=csv autocomplete /psasmaster/src/xxx.com/xxx/messagehub/main.go c246` Yeah, in this call, the absolute path to the Go file should be passed. I don't see why it isn't. Also, this is very strange:
``` 
   with GOPATH: /home/rohits/p1/p1trunk/psasmaster:/home/rohits/Desktop/gocode:/home/rohits/Work/vault
...
   with GOPATH: /home/rohits/ipas/ipastrunk/psas.mastermgmt:/home/rohits/Desktop/gocode:/home/rohits/Work/vault
``` 
These two calls should have the same value of GOPATH. Which GOPATH do you actually have set?

**Comment by huskercane** [comment]
Thank You for reviewing,

I reviewed, they are same on my eclipse.

When I pasted for the bug, I changed it to be not too specific. and I messed up.

Apologies

Does my current project has to be in GOPATH for this to work? I am not clear how it will resolve path, especailly since path that it is sending to gocode starts with a "/"

oracle seem to parse properly

>> Running: /usr/local/go/bin/oracle -pos=/tmp/_goclipse5396028754003913443/src/describe_temp/describe.go:#8,#8 -format=json describe describe_temp
   with GOPATH: /tmp/_goclipse5396028754003913443
{
	"mode": "describe",
	"describe": {
		"desc": "definition of package \"describe_temp\"",
		"pos": "/tmp/_goclipse5396028754003913443/src/describe_temp/describe.go:1:9",
		"detail": "package",
		"package": {
			"path": "describe_temp",
			"members": [
				{
					"name": "main",
					"type": "func()",
					"pos": "/tmp/_goclipse5396028754003913443/src/describe_temp/describe.go:14:6",
					"kind": "func"
				},
				{
					"name": "wg",
					"type": "sync.WaitGroup",
					"pos": "/tmp/_goclipse5396028754003913443/src/describe_temp/describe.go:11:2",
					"kind": "var"
				}
			]
		}
	}
}

**Comment by huskercane** [comment]
Problem with F3 is definetly wrong path, error pop up has "/"<projectname><path to file>.

file is correct, not sure if eclipse can resolve it though

**Comment by bruno-medeiros** [comment]
No, your project does not have to be in the GOPATH set in preferences (it gets added implicitly when using tools on your project).
I'm gonna fire up my Linux box to see if I can replicate this.

**Comment by bruno-medeiros** [comment]
I tried in my Linux box but couldn't replicate it :/

**Comment by huskercane** [comment]
I am curious what eclipse version do U have? I am using eclipse mars.

Can I get something that will help debug this?

**Comment by bruno-medeiros** [comment]
> Can I get something that will help debug this?

Any chance I can get you to try to run DDT under a debugger, to try to find out what's causing this? I've updated the instructions in https://github.com/GoClipse/goclipse#developers-guide , it should make it fairly straightforward to setup a workspace where one can debug DDT itself.

**Comment by tbenbrahim** [comment]
I have the same problem on eclipse Mars. Basically every time I enter a period, I get a popup with text OK, a single OK button and caption unable to run "starting code server". 

The gocode log shows something like the following in red:
c:\Users\TONY~1.BEN\AppData\Local\Temp\_goclipse8921638740882086858\src\describe_temp\describe.go:205:6: expected selector or type assertion, found 'return' (and 2 more errors)

The error message is correct, the code is not syntactically correct when I type period, and after I press the OK button on the error dialog, I get normal code completion. This happens every time I enter a period

**Comment by huskercane** [comment]
The two options to setup projects.

This option works
"The project location is a subfolder of the 'src' folder of some GOPATH entry. The project will then consist of the Go source packages contained there."

unfortunately I cannot use this. I am using Rational Team Concert and we import all eclipse projects in workspace.

so I am more like option 2
"The project location is not part of any GOPATH entry."

My current project in part of gopath.

it is one of the several projects, I made it of type Go before checking it in so it is proper. as I said before not in GOPATH.

and completion does not work in this case. it is only go project so no siblings.

Did U test option 2?

WIll try to import PDE also.

**Comment by huskercane** [comment]
I created 

sudo ln -s /home/rohits/xxx/xxxx/xxx.yyyy/

and everything works. so for option 2 I think reading path is not correct. will look how to solve it

**Comment by bruno-medeiros** [comment]
I'm still somewhat confused as to how your Go setup is. So, you say your Go projects are not part of a pre-existing GOPATH entry. Ok. So then, when you try autocomplete on a Go file, what location is your Go file, relative to the project ?

**Comment by bruno-medeiros** [comment]
Closing, not enough info provided.
