### ISSUE TITLE
Can't stop on breakpoint while debugging

### ISSUE THREAD

**Issue by enp** [GoClipse/goclipse#139]
Execution can't stop on breakpoint while debugging. Compilation looks like:

```
====================  Starting Go build  ====================
************  Building Go project: GApp  ************
>> Running: /usr/lib64/golang/bin/go install -v -gcflags -N -l ./...
   with GOPATH: /home/enp/workspace/GApp:/home/enp/golang
app
   ^^^ Terminated, exit code: 0 ^^^
************  Build terminated.  ************
```

On running in debug mode I see:

```
GNU gdb (GDB) 7.5.0.20121002-alt3 (ALT Linux)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-alt-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
No source file named /home/enp/workspace/CApp/src/CApp.c.
```

File /home/enp/workspace/CApp/src/CApp.c exists but I don't know why it was mentioned. This is C test application, which can be debugged correctly.

I use Eclipse IDE for C/C++ Developers (Mars 4.5) with GoClipse 0.11.1.v201507011626 (and with #135 fixed) and go version 1.4.2 linux/amd64.

**Comment by bruno-medeiros** [comment]
Can you try it with Eclipse 4.4 (Luna) ? This is likely a problem where latest Goclipse is not compatible with the CDT in Eclipse Mars

**Comment by bruno-medeiros** [comment]
If it worked with Eclipse 4.4, then the new Goclipse version should have that fixed: https://github.com/GoClipse/goclipse/releases/tag/v0.11.2

**Comment by enp** [comment]
Thanks, new release works on 4.5

But it works only for projects with separate $GOPATH (with src, pkg, bin in project tree).

I have some projects with the shared $GOPATH (inside $GOPATH/src), but I can't debug and even run them via Run menu due to error: Process path is empty.

**Comment by bruno-medeiros** [comment]
Fixed in 0.11.2

**Comment by bruno-medeiros** [comment]
> But it works only for projects with separate $GOPATH (with src, pkg, bin in project tree).
> 
> I have some projects with the shared $GOPATH (inside $GOPATH/src), but I can't debug and even run them via Run menu due to error: Process path is empty.

I've replicated that, opened https://github.com/GoClipse/goclipse/issues/140

A workaround is to put something like "xxx/.." in the "Go main package" field of the launch

**Comment by enp** [comment]
Thanks, it really helps now
