### ISSUE TITLE
Feature to run gofmt automatically when saving file

### ISSUE THREAD

**Issue by tianzhou** [GoClipse/goclipse#142]

**Comment by bruno-medeiros** [comment]
No. It would be an interesting feature to add though.

**Comment by LindsayBradford** [comment]
+1

**Comment by EnglishCriminal** [comment]
+1

**Comment by jumpinjan** [comment]
+1

**Comment by maxgarvey** [comment]
+1

**Comment by dan9186** [comment]
+1

**Comment by bruno-medeiros** [comment]
Ok... lot's of interest :) I'll see about having a look at this on the next iteration.

**Comment by jumpinjan** [comment]
Thank you!!



Janice Gluck

[cid:image001.png@01CF858C.32055680]<http://www1.good.com/>[http://media.www1.good.com/images/icon-em-sig-facebook.png]<https://www.facebook.com/goodformobile>[http://media.www1.good.com/images/icon-em-sig-twitter.png]<https://twitter.com/GOOD_technology>[http://media.www1.good.com/images/icon-em-sig-linkedin.png]<https://www.linkedin.com/company/good-technology>[http://media.www1.good.com/images/icon-em-sig-youtube.png]<https://www.youtube.com/user/GoodForMobile>

**Comment by aaudis** [comment]
+1

**Comment by parhamdoustdar** [comment]
Is this feature currently implemented? I can't see my code being formatted on save.

Also, is it possible to define our own commands when saving? I would like to run `golint` and `go vet` and `go test`, too.

**Comment by qianzhangxa** [comment]
+1!
