### ISSUE TITLE
fetching countrycode fails

### ISSUE THREAD

**Issue by donghwicha** [GoClipse/goclipse#143]
i got trouble with downloading some file with installing 

At installing software, fetching country code fails with this url 
And I'm living at south korea not china :)

Any advice?

"http://www.eclipse.org/downloads/download.php?format=xmlfile=/releases/mars/201506241002/"

**Comment by bruno-medeiros** [comment]
Where exactly is that URL shown ? Can you explain more, or post a screenshot?

**Comment by bruno-medeiros** [comment]
closing, not enough info
