### ISSUE TITLE
How to get started with existing code

### ISSUE THREAD

**Issue by moander** [GoClipse/goclipse#144]
I'm new to both go and Eclipse, so please bear with me.

I want to fork https://github.com/michaelmacinnis/oh and do some modifications, but I'm not able to figure out how workspaces, gopaths, and projects should be configured for scenarios like this.

Could someone please point me in the right direction? :)

**Comment by bruno-medeiros** [comment]
You should read https://golang.org/doc/code.html to get acquainted with how Go workspaces work. After you have created a Go workspace by specifying one in the GOPATH variable, run `go get github.com/michaelmacinnis/oh`

This will download the sources of that project into your Go workspace (under `src`). After that, create a new Go project in Eclipse, and in the Project wizard, choose the project location to be where the `oh`directory, is, for example: `D:\devel\tools.Go\go-workspace\src\github.com\michaelmacinnis\oh`. This should get you started.
