### ISSUE TITLE
Critical UX problem: Keeps opening error dialogs, opening console etc on temporary auto complete or oracle errors, interrupting my work

### ISSUE THREAD

**Issue by hnsl** [GoClipse/goclipse#145]
When an error dialog or console opens I have to switch to the mouse to close it. This happens quite often if the cursor happen to be placed incorrectly in the code or due to temporary reasons. It's much, much better to not display the error at all rather than interrupting the user. Log it to some error file or something.

**Comment by bruno-medeiros** [comment]
What error dialogs are you getting? Is it errors related to gocode?

And what consoles are opening? New opened consoles should not be getting the focus of the keyboard.

**Comment by bruno-medeiros** [comment]
Closing, not enough info.
