### ISSUE TITLE
Tabs and spaces

### ISSUE THREAD

**Issue by akutz** [GoClipse/goclipse#146]
Hi All,

Even when I set the preferences in Eclipse to use spaces instead of tabs, formatting the document results in tabs. I searched, and this does not appear to be a known issue.

![image](https://cloud.githubusercontent.com/assets/101085/9094016/34464616-3b75-11e5-9d54-f0813a081db7.png)
![image](https://cloud.githubusercontent.com/assets/101085/9094023/3dfbdfd6-3b75-11e5-905c-c7aafd4b067f.png)
![image](https://cloud.githubusercontent.com/assets/101085/9094031/45eccd9a-3b75-11e5-9fe8-7fb4e5aae84d.png)

**Comment by bruno-medeiros** [comment]
How are you formatting the document, did you use "Go Format (gofmt)" ?

**Comment by akutz** [comment]
Hi @bruno-medeiros,

Yes, and as it turns out this is a non-issue as I've learned far more about go and now understand that tabs are required with gofmt. Thanks for your reply!

**Comment by bruno-medeiros** [comment]
Yeah, those preferences settings only affect auto-indentation when Enter is pressed in the editor (or when Tab is pressed to indent several lines, etc.).
It doesn't seem like gofmt allows customizing its indentation behavior.
