### ISSUE TITLE
Error dialog before every code completion

### ISSUE THREAD

**Issue by tbenbrahim** [GoClipse/goclipse#148]
On eclipse Mars on Windows., every time I enter a period, I get a popup with text OK, a single OK button and caption error executing "running gocode server". 

The gocode log shows something like the following in red:
c:\Users\TONY~1.BEN\AppData\Local\Temp\_goclipse8921638740882086858\src\describe_temp\describe.go:205:6: expected selector or type assertion, found 'return' (and 2 more errors)

The error message is correct, the code is not syntactically correct when I type period, and after I press the OK button on the error dialog, I get normal code completion. This happens every time I enter a period

![image](https://cloud.githubusercontent.com/assets/1153429/9153947/30ba7afe-3e3f-11e5-8ae8-e222651c0ef3.png)

**Comment by bruno-medeiros** [comment]
Please update Goclipse. 0.12.0 was re-release a couple of time, that should be fixed in the latest RC version.
