### ISSUE TITLE
Suggestion: Custom Build Targets

### ISSUE THREAD

**Issue by tbenbrahim** [GoClipse/goclipse#149]
Add the ability to add custom make targets
for example, I may want targets for:
-go test -coverprofile=coverage.out
-go tool cover -html=coverage.out
-godep -save
etc...

**Comment by bruno-medeiros** [comment]
Whats the advantage of running those during the build cycle? They don't produce build errors (well, not more than the normal build at least). Even the build target "[run-tests]" is something I added experimentally, not sure how useful it will be in practice, for big projects.

If you just want the convenience of calling such external commands from Eclipse, you can create an "External Command" launch configuration.

I guess the only advantage of having it in the Build Targets is that it sets up the Go environment (GOPATH, etc.) automatically for the called command, hum..

**Comment by Jumfer** [comment]
I actually liked this idea, run targets also work but would have been nice in the one I'm building now where the build has one go generate and one go install that need to be run. Or maybe I misunderstood and I can have several commands inside the "build" targe? I don't need several custom build targets just several commands in the one build target.... If this is considered spam then please remove and excuse

**Comment by bruno-medeiros** [comment]
You can only have one command in each Build Target, yes, but as a workaround, you can invoke a shell script that calls multiple commands. For example: `bash -c 'go generate; go build" '`, that might work.
I might also work on adding support for creating new Build Targets, not just the predefined ones.

**Comment by markus-wa** [comment]
I would like to see this issue reopened.

One advantage of custom build targets would be that you can have separate targets for 'release' (read performance testing) and debugging (`-I -N` flags) and additional ones for tests, benchmarks, coverage, profiling etc.

It would also allow to create targets for code generation for example.

External commands also have the drawback of not being checked into version control.

**Comment by bruno-medeiros** [comment]
Ok, I've created a new issue: https://github.com/GoClipse/goclipse/issues/241
