### ISSUE TITLE
How to cross compile by project? 

### ISSUE THREAD

**Issue by lukexue** [GoClipse/goclipse#152]
Need to build x86/x64 in difference project. 
How to set environment variable 
GOOS=linux 
GOARCH=386 
CGO_ENABLED=0 
go build ...
in other project?

**Comment by bruno-medeiros** [comment]
Unfortunately it's not possible at the moment. I'll see if I can add support for that in next version. In the meanwhile, a workaround is to start a difference Eclipse instance in a different Eclipse workspace (and configure a different GOROOT in that other Eclipse instance)

**Comment by bruno-medeiros** [comment]
I've added support for this in ~master, next version will have this.
