### ISSUE TITLE
Content assist does not show all members

### ISSUE THREAD

**Issue by RomanSaveljev** [GoClipse/goclipse#154]
GoClipse version: `0.12.1.v201508`

I have a package called `receiver` with the following code:

```go
package receiver

type Signature struct {
	Rolling string
	Strong string 
}

const CHUNK_SIZE = 4096

type Chunk struct {
	Signature
	Data [CHUNK_SIZE]byte
}
```

And I am trying to use `receiver.Chunk` in another package:

```go
package transmitter

import (
    ...
)

type Chunk receiver.Chunk
```

Calling content assist (Ctrl+Space) on `this *Chunk` only show:

* `Data: [4096]byte`
* `Signature: receiver.Signature`

It should show members from `Signature` (the compiler understands it, when I type it)

**Comment by bruno-medeiros** [comment]
I'm afraid that would be gocode limitation, so you'd have to bring it up with that project: https://github.com/nsf/gocode . Could be worth opening an issue there then.

**Comment by RomanSaveljev** [comment]
Thanks for quick assessment. I could prepare a bug report for gocode. Is there some easy way to reproduce it using gocode alone?

**Comment by bruno-medeiros** [comment]
Probably what you said above will be enough to determine the problem. But also, if you invoke Content Assist on the Eclipse Go editor, and then open the console page `Oracle/gocode log` in the console view, it will show the command line that was used to invoke gocode, so you could add that info as well.
