### ISSUE TITLE
Builds break using latest Go 1.5.1

### ISSUE THREAD

**Issue by Russtopia** [GoClipse/goclipse#155]
I don't have the exact errors at hand as I downgraded back to just 1.5 to get things going again... but builds spit out tons of complaints about the go stdlibs for x64.

Platform: Win7 x64
Eclipse Platform

Version: Mars (4.5)
Build id: I20150603-2000

Goclipse v0.12.1.v201508251600

go version: 1.5.1 windows/amd64

**Comment by bruno-medeiros** [comment]
I upgraded to 1.5.1, and had no problem compiling my Go workspace. Was your 1.5 version also amd64 like the 1.5.1 you tried? In any case, try deleting the bin/ and pkg/ folders of your Go workspace, see if the build works then.

**Comment by bruno-medeiros** [comment]
Closing, not enough info provided.
