### ISSUE TITLE
Support for Go 1.5 vendoring experiment

### ISSUE THREAD

**Issue by samherrmann** [GoClipse/goclipse#157]
It would be great to see support for the vendoring experiment that was added in Go 1.5 (https://golang.org/cmd/go/#hdr-Vendor_Directories)

Currently the build that GoClipse kicks off on save fails with "cannot find package error" for the packages that are in the ```/vendor``` subdirectory. The command that GoClipse runs is ```C:\Go\bin\go.exe install -v -gcflags "-N -l" ./...```. As expected, I can reproduce the error from the command line by executing the same command. If I run ```C:\Go\bin\go.exe install -v -gcflags "-N -l"``` (without ```./...```) from the root of my project, the build is successful.

Perhaps the solution is to set the build command based on the presence of the environment variable ```GO15VENDOREXPERIMENT=1```?

**Comment by akutz** [comment]
HI @samherrmann,

I too wished this would exist, so I forked the project and produced a build where it does. https://github.com/akutz/goclipse/releases/tag/v0.12.1-go15vendoring

**Comment by samherrmann** [comment]
hey @akutz, thanks for the patch, that's awesome :)

**Comment by bruno-medeiros** [comment]
@samherrmann are you sure removing the `./...` on the command line makes any difference? It doesn't for me (assuming you invoke it in the right directory). I only works if by setting the GO15VENDOREXPERIMENT to 1.

You can make this work in Eclipse as well by setting the GO15VENDOREXPERIMENT environment variable globally. This means vendor mode will be enabled for all projects though, but that seems fine for now.

**Comment by samherrmann** [comment]
@bruno-medeiros I narrowed down my issue. Oddly enough, I'm getting the issue only with one particular package. With that observation I'm starting to doubt that there's anything that needs to be changed in GoClipse after all. Nonetheless, here are the steps to reproduce my problem...

Set up the folder structure as shown below. Here you can see that the Eclipse project is opened from the ```/myproj``` folder (note the .project file):
```
C:/gopath/
    |
    bin
    pkg
    src/
        |
        myorg/
            |
            myproj/
                |
                .project
                main.go
                vendor/
```

Now set the following environment variables:
````
GOPATH=C:/gopath
GO15VENDOREXPERIMENT=1
````

Install the "gracefull" package: ```go get gopkg.in/tylerb/graceful.v1```
This will install the package in ```/gopath/src/```. Move the package (and any of its dependencies that were downloaded) from ```/gopath/src``` into the ```/vendor``` folder.

The main.go file looks as follows:
```
package main

import (
  	"gopkg.in/tylerb/graceful.v1"
)

func main() {
  // just some dummy code to make use of the graceful package... 
  graceful.Run(":3000",0, nil)
}
```

Attempting to build this project with the command ```go install -v -gcflags "-N -l" ./...``` from the ```/myproj``` directory will throw the errors shown below. Running the same command without the ```./...``` works. If you move the vendor packages back into the ```/gopath/src/``` directory, and set ```GO15VENDOREXPERIMENT=0``` then both commands, with and without the ```./...```, work.

```
vendor\golang.org\x\net\html\charset\charset.go:20:2: cannot find package "golang.org/x/text/encoding" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\encoding (vendor tree)
	C:\Go\src\golang.org\x\text\encoding (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\encoding (from $GOPATH)
vendor\golang.org\x\net\html\charset\charset.go:21:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\encoding\charmap (vendor tree)
	C:\Go\src\golang.org\x\text\encoding\charmap (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\encoding\charmap (from $GOPATH)
vendor\golang.org\x\net\html\charset\table.go:8:2: cannot find package "golang.org/x/text/encoding/japanese" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\encoding\japanese (vendor tree)
	C:\Go\src\golang.org\x\text\encoding\japanese (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\encoding\japanese (from $GOPATH)
vendor\golang.org\x\net\html\charset\table.go:9:2: cannot find package "golang.org/x/text/encoding/korean" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\encoding\korean (vendor tree)
	C:\Go\src\golang.org\x\text\encoding\korean (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\encoding\korean (from $GOPATH)
vendor\golang.org\x\net\html\charset\table.go:10:2: cannot find package "golang.org/x/text/encoding/simplifiedchinese" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\encoding\simplifiedchinese (vendor tree)
	C:\Go\src\golang.org\x\text\encoding\simplifiedchinese (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\encoding\simplifiedchinese (from $GOPATH)
vendor\golang.org\x\net\html\charset\table.go:11:2: cannot find package "golang.org/x/text/encoding/traditionalchinese" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\encoding\traditionalchinese (vendor tree)
	C:\Go\src\golang.org\x\text\encoding\traditionalchinese (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\encoding\traditionalchinese (from $GOPATH)
vendor\golang.org\x\net\html\charset\table.go:12:2: cannot find package "golang.org/x/text/encoding/unicode" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\encoding\unicode (vendor tree)
	C:\Go\src\golang.org\x\text\encoding\unicode (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\encoding\unicode (from $GOPATH)
vendor\golang.org\x\net\html\charset\charset.go:22:2: cannot find package "golang.org/x/text/transform" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\text\transform (vendor tree)
	C:\Go\src\golang.org\x\text\transform (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\text\transform (from $GOPATH)
vendor\golang.org\x\net\http2\h2i\h2i.go:39:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\golang.org\x\crypto\ssh\terminal (vendor tree)
	C:\Go\src\golang.org\x\crypto\ssh\terminal (from $GOROOT)
	C:\dev\gopath\src\golang.org\x\crypto\ssh\terminal (from $GOPATH)
vendor\gopkg.in\tylerb\graceful.v1\tests\main.go:7:2: cannot find package "github.com/codegangsta/negroni" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\github.com\codegangsta\negroni (vendor tree)
	C:\Go\src\github.com\codegangsta\negroni (from $GOROOT)
	C:\dev\gopath\src\github.com\codegangsta\negroni (from $GOPATH)
vendor\gopkg.in\tylerb\graceful.v1\tests\main.go:8:2: cannot find package "github.com/tylerb/graceful" in any of:
	C:\dev\gopath\src\myorg\myproj\vendor\github.com\tylerb\graceful (vendor tree)
	C:\Go\src\github.com\tylerb\graceful (from $GOROOT)
	C:\dev\gopath\src\github.com\tylerb\graceful (from $GOPATH)
```

**Comment by bruno-medeiros** [comment]
I did  a `go get gopkg.in/tylerb/graceful.v1` on a clean Go workspace, and I couldn't even get it to build it afterwards with `go build ./...`, and this without even doing any of the vendor changes. I get errors similar to yours:

```
golang.org\x\net\html\charset\charset.go:20:2: cannot find package "golang.org/x/text/encoding" in any of:
        D:\devel\tools.Go\go\src\golang.org\x\text\encoding (from $GOROOT)
        D:\devel\DDT\_runtime\GoTest2\src\golang.org\x\text\encoding (from $GOPATH)
```
...

As such I don't think this has anything to do with Goclipse (or even GO15VENDOREXPERIMENT). Closing the issue as such, but let me know if anything relevant changes.

Also, you can change the build command used for your project, so maybe changing it to `go install -v myorg/myproj` will work.
