### ISSUE TITLE
"Go Build" console keeps focusing 

### ISSUE THREAD

**Issue by baconalot** [GoClipse/goclipse#158]
The "Go build" console always pops up when building. The setting "Go->Build Console->Activate on error" has no effect whatsoever. 
Also "Run/Debug->Console->Show when writing to (out|error)" are both off.
Maybe related to #145?

**Comment by bruno-medeiros** [comment]
Those options are not supposed to affect the build console popping up when a build is started.

It would be nice to add such an option though, but unfortunately, due to a stupid Eclipse limitation, it's not possible, unless I rewrite lots of their code. :(

**Comment by joegrasse** [comment]
I have this same problem as well. This didn't always use to be the case. Not sure what change this started happening.

**Comment by rillig** [comment]
Me too. The Console view always puts itself in the foreground when building, trying to get my attention. I prefer to use the Markers view for looking at the build errors.

**Comment by joegrasse** [comment]
I don't remember which goclipse update caused this, but I also have this problem.

**Comment by joegrasse** [comment]
@bruno-medeiros  Do you think you will do a release with this fix soon?

**Comment by bruno-medeiros** [comment]
yup the next release should be coming out soon, 1-2 weeks

**Comment by joegrasse** [comment]
ok, thanks for the update.
