### ISSUE TITLE
Problem downloading Go oracle and gocode

### ISSUE THREAD

**Issue by wks** [GoClipse/goclipse#159]
In the Preference -> Go -> Tools dialog, there are buttons for downloading Go oracle and gocode. But I am having problem with my installations:

1. On a Windows machine, Git is, by default, only invokable from its own bash shell, not the CMD shell.
2. On an OSX machine where I installed Go via [Homebrew](http://brew.sh/), the executable is in `/usr/local/bin`, which I set to be part of the PATH in my shell's initialization script (.zshenv, or .bashrc), but not in the global PATH which is seen by executing Eclipse.app.

In both cases, directly invoking the command will fail, but I can paste the command into my chosen shell to run successfully.

I suggest that instead of having the UI like this (`(...)` denotes buttons and `[...]` denotes textboxes):
```
Go oracle path: [......] (Browse)
(Download Go oracle (run: `go get -u golang.org/x/tools/cmd/oracle`))
```
Use this:
```
Go oracle path: [......] (Browse)
You can download Go oracle by executing the following command:
[go get -u golang.org/x/tools/cmd/oracle] (run now)
```
The point is that the command is now in a (probably read-only) text box and can be copied and pasted to my own shell to execute.

**Comment by bruno-medeiros** [comment]
You can just click the button anyways, and if the command fails, copy the command into the clipboard from the Go build console.

(Also, from my understanding, Git on Windows works fine on any shell, as long as the Git executable is on the path.)
