### ISSUE TITLE
Cannot find "Create project from existing source"

### ISSUE THREAD

**Issue by chuong** [GoClipse/goclipse#164]
Dear developers,
Somehow there is no option to import existing Go source codes into Eclipse. The only option available is File->New->Go Project. For example running:
$ go get -u github.com/odeke-em/drive/cmd/drive
will download the source to ~/go/bin/src/github.com/odeke-em/drive. How to import this existing project in to Eclipse using GoClipse?
I cannot find any instructions to do this. 
My machine is Ubuntu 14.04 64bit with Eclipse 4.5.1 and Java 1.8.0_60.
Thanks.

**Comment by LindsayBradford** [comment]
You need to create a new go project regardless, but select a pre-existing directory containing the old project files when you get to the project wizard step below:

![nreprojectoldlocation](https://cloud.githubusercontent.com/assets/1407701/10472381/20514640-7263-11e5-8dfb-0ab936e3cf5f.png)

My understanding is that this is how it works for eclipse, regardless of whether you're dealing with Go or some other language.

**Comment by chuong** [comment]
Thanks so much for your quick reply Lindsay. 
I also tried exactly that and GoClipse showed a warning below

![goclipsenotification](https://cloud.githubusercontent.com/assets/776061/10472505/c60aacda-726c-11e5-8eaa-2eaf3d36c9c4.png)

and created bin/ and pkg/ folder inside the project folder.
I don't understand exactly what this means but this behaviour seems not consistent with Go folder structure.

**Comment by LindsayBradford** [comment]
Interesting... without knowing the specifics of your project layout, I'd have expected the Eclipse .project file to be in a parent directory, where /src, /bin and /pkg are all sub-directories.  The root directory of the project shouldn't have go source files. 

Ahh.. here we are... it's a golang "workspace" concept, described here:

https://golang.org/doc/code.html#Organization

**Comment by chuong** [comment]
I have Go installed at ~/go and Google Drive package installed at ~/go/bin/src/github.com/odeke-em/drive.

I just figured out a way to get rid of the warning and the folder structure is consistent. That is to choose ~/go/bin/ as the project folder to import into Eclipse. This folder contains bin/, pkg/ and src/ folders. From that projects under ~/go/src/ folder will automatically compiled and the executables are put at ~/go/bin/bin/ folder. This is consistent with how Go behaves as described at https://golang.org/doc/code.html.

**Comment by LindsayBradford** [comment]
Well... I guess if that works for you, so be it.  For me, housing a /src directory inside a /bin directory generates a pretty rank code-smell I'd rather not experience.

**Comment by chuong** [comment]
It's my bad. Somehow I set  
export GOPATH=$GOROOT/bin 
This explains why I have my project folder started at ~/go/bin/bin/.
$GOPATH should points to my project workspace folder as mentioned at https://golang.org/doc/code.html#GOPATH 
Cheers.

**Comment by bruno-medeiros** [comment]
Thx @LindsayBradford for the explainations.

> My understanding is that this is how it works for eclipse, regardless of whether you're dealing with Go or some other language.

This is usually not the case though, for other Eclipse IDEs like JDT or CDT. On those one usually uses the "Import Project" wizard, although using the "New Project" Wizard should work as well. This might be a bit confusing to users or Goclipse who are familiar with other Eclipse IDEs. I shall a note to the UserGuide to clarify this.

**Comment by LindsayBradford** [comment]
Heh... there's my obligation to "learn something new each day" fulfilled for today. :)
