### ISSUE TITLE
Installed GoEclipse now Eclipse cannot be started

### ISSUE THREAD

**Issue by steowens** [GoClipse/goclipse#165]
I just followed the installation instructions for installing goeclipse using the update site.  Now eclipse fails to start.

**Comment by bruno-medeiros** [comment]
In the Eclipse workspace directory, what are the contents of the .metadata/.log file?

**Comment by steowens** [comment]
I don't know.  I ended up having to delete my eclipse installation and re-install the entire thing just finished setting up all my old plugins.  I can say that the eclipse that it broke was older than Mars, but your installation shouldn't destroy someones setup it should fail more gracefully.

**Comment by bruno-medeiros** [comment]
It shouldn't destroy another Eclipse installation and to be honest I very much doubt Goclipse was the fault of it. But I can't help without more info. 
The Eclipse workspace directory is not the same as the installation directory, it's where projects are created by default (and it's a directory you choose the first time Eclipse starts up). So unless you explicitly deleted the workspace directory, the .metadata/.log file should still be there.

**Comment by steowens** [comment]
I re-installed eclipse and am back on line.  No longer able to reproduce the error.  The error started after a series of plugin installations.  Last of which was goeclipse.
