### ISSUE TITLE
Editor: documention hover/tooltip

### ISSUE THREAD

**Issue by wolfgangmeyers** [GoClipse/goclipse#173]
When using the java editor, hovering the mouse over a method invocation shows a tooltip with the documentation for that method. I find it very handy, as it saves me from having to open up a new tab to look at the docs before using it.

Using goclipse version 0.13.0.v201510291605

**Comment by wolfgangmeyers** [comment]
Not sure if this is relevant or not - http://www.java2s.com/Code/Java/SWT-JFace-Eclipse/HowtoimplementhoverhelpfeedbackusingtheMouseTrackListener.htm

**Comment by bruno-medeiros** [comment]
The Eclipse UI side code is there already, but it needs Go language backend support. We would need gocode (or another tool) to provide this support. See for example: https://github.com/nsf/gocode/issues/150

**Comment by parhamdoustdar** [comment]
What about using `godoc`?

**Comment by bruno-medeiros** [comment]
> What about using godoc?

could be a good choice. I've found several weeks about a bunch of Go tools I didn't know, such as `godoc`, `godef`, and others (see: https://marketplace.visualstudio.com/items?itemName=lukehoban.Go) 
They look promising, but I haven't had the time to try to integrate them yet.

**Comment by bruno-medeiros** [comment]
> What about using godoc?

Could be a good choice. I've found out several weeks ago about a bunch of Go tools I didn't know, such as `godoc`, `godef`, and others (see: https://marketplace.visualstudio.com/items?itemName=lukehoban.Go) 
They look promising, but I haven't had the time to try to integrate them yet.

**Comment by cyrille-gachot** [comment]
+1: it would be really helpful

**Comment by ashwin** [comment]
+1
