### ISSUE TITLE
Function invocation auto-fill

### ISSUE THREAD

**Issue by wolfgangmeyers** [GoClipse/goclipse#174]
It would be nice if using the code completion to fill in a function call, if it also created an invocation template with all of the named parameters as in the java editor.

For instance if I had a function:

```
func Breakfast(spam bool, numEggs int, gravy bool) error {
...
}
```

Then selecting "Breakfast" from the dropdown after typing ctrl-space would fill out a full invocation:

```
Breakfast(spam, numEggs, gravy)
```
This might not compile, but it would be a nice reminder of the order of the arguments for someone who isn't 100% familiar with the api in question.

Using goclipse version 0.13.0.v201510291605

**Comment by bruno-medeiros** [comment]
Hum, I might be able to add this fairly easily.

**Comment by wolfgangmeyers** [comment]
That would be great! If there is anything I can do to help, let me know.

**Comment by wolfgangmeyers** [comment]
Thanks!!
