### ISSUE TITLE
Saving files doesn’t trigger build anymore

### ISSUE THREAD

**Issue by rillig** [GoClipse/goclipse#175]
Environment:
* GoClipse version: e7b0f8e257d43230c7380ffec6f341a3f93750c4
* Operating system: Windows 10
* Architecture: amd64
* Eclipse error log: nothing

I had installed GoClipse 0.13.0. Whenever I saved a file, `go build` was run.

Now I installed the version from the above-mentioned commit, built from source. It works fine, and especially the console is nicely quiet (see #158). But when I save a file, no build is triggered anymore. Now I have to trigger a build manually to see any syntax errors I made. (By the way, [x] Build Automatically is checked, so that is not the problem here.)

**Comment by bruno-medeiros** [comment]
It's not a bug, that behavior changed on the version in master:
> Project builder is no longer invoked when workspace "Build Automatically" setting is enabled and a file is saved. (this was considered a misfeature anyways)

(from  https://github.com/GoClipse/goclipse/blob/master/documentation/ChangeLog.md )

It might not be obvious at first, but this functionality interferes with some current functionality, and other functionality that I am planning to add in the future (such as on-the-fly build). Even from a UX perspective it's not ideal: what I would recommend instead is to enable the Workspace preference "Save automatically before build", and then press "Ctrl+B" whenever you want to build (this will save all dirty editors before building). 

If you really want the previous functionality, you can open a project's Properties, go to "Builder" page, select the "Go Project Builder" and press "Edit...". Then, there is a "During Auto-build" checkbox that you can enable.

**Comment by rillig** [comment]
Thanks for the explanation. I’ve changed my build settings accordingly.
