### ISSUE TITLE
Outline not showing up for different func declaration

### ISSUE THREAD

**Issue by lionelmessi** [GoClipse/goclipse#177]
This is not showing up in outline

    func (this *MainController) RegisterJson() {
    }

but this is showing up fine

    func  RegisterJson (this *MainController) {
    }

**Comment by lionelmessi** [comment]
I was wondering if anything could be done to resolve this. Quite difficult to browse to functions in long files without an outline.

**Comment by bruno-medeiros** [comment]
I might be able to improve this in the near future, I'll have to take a better look though.

**Comment by lionelmessi** [comment]
thank you.

**Comment by bruno-medeiros** [comment]
It's a partial fix here: Now it outline works correctly when editor is saved, but not if the editor is dirty.
