### ISSUE TITLE
GoClipse v0.13 conflicts with C/C++ Dev Tools v8.8.0.x

### ISSUE THREAD

**Issue by rbondi** [GoClipse/goclipse#181]
Bug: It's not possible to have both GoClipse v0.13 and C/C++ Development Tools v 10 installed together.

I'm using Eclipse Version: Mars.2 (4.5.2), trying to install GoClipse 0.13.0.v201510291605.

Eclipse says there is a conflict with the Eclipse C/C++ Development Tools (CDT), and gives me the option of either uninstalling CDT, or installing GoClipse v0.9. See screenshots below.

**Comment by rbondi** [comment]
Eclipse wouldn't let me install v0.13. It suggested I install v0.9 instead:

![nocando](https://cloud.githubusercontent.com/assets/81764/12592735/8a1c8bbe-c422-11e5-8006-363f20320e22.png)

Eclipse said this was the problem:

![whynocando](https://cloud.githubusercontent.com/assets/81764/12592751/96c530dc-c422-11e5-9d8d-fb555f10ee0e.png)

**Comment by bruno-medeiros** [comment]
There is no C/C++ Dev Tools v10, the latest released version is 8.8.0, and the upcoming version is 9.0.

Anyways, I can fix this, but only when the next CDT version is actually released.

**Comment by rbondi** [comment]
Sorry, my mistake in the title of the bug: as you say, the screenshot of the conflict shows v8, not v10 of CDT. I've updated the title of the bug to reflect that.

**Comment by bruno-medeiros** [comment]
In case, the issue is the same, you seem to using some beta/integration/nightly build of CDT (judging from the build string "8.8.0.201601150"), not a released version. The last released version of CDT is 8.8 relased on October 2, 2015, not 2016

**Comment by sprigogin** [comment]
> Anyways, I can fix this, but only when the next CDT version is actually released.
What prevents you for relaxing version constraints sooner so that people could use GoClipse together with pre-release CDT builds?

**Comment by bruno-medeiros** [comment]
Currently Goclipse uses a lot of API from CDT, some of it internal (unfortunate, but necessary), so it needs testing and review to build against CDT release that change API major version numbers.

**Comment by ychsieh** [comment]
The same issue here. Any solutions so far?

**Comment by sprigogin** [comment]
I solved this problem locally by building a more forgiving version of
GoClipse. It's been in use for almost two months with no issues.

-sergey

**Comment by rbondi** [comment]
+1
I've been using spiroggin's version for those two months, no issues.
/rb

**Comment by ychsieh** [comment]
Could you tell me how to build a more forgiving version of GoClipse?

**Comment by sprigogin** [comment]
I just relaxed the CDT version constraints in MANIFEST.MF files.

-sergey

**Comment by ychsieh** [comment]
https://github.com/GoClipse/goclipse/blob/master/plugin_ide.core/META-INF/MANIFEST.MF
Do you mean this file? I am new to this and don't know where to begin...

**Comment by sprigogin** [comment]
Don't remember exactly what files I changed. Look for references to cdt in
MANIFEST.MF and feature.xml files.

-sergey

**Comment by bruno-medeiros** [comment]
@ychsieh You'll need to change the `
      <import feature="org.eclipse.cdt.gnu.dsf" version="8.7.0" match="compatible"/>
      <import feature="org.eclipse.cdt.platform" version="8.8.0" match="compatible"/>
` lines in feature.xml , and perhaps some version numbers in  https://github.com/GoClipse/goclipse/blob/master/plugin_ide.debug/META-INF/MANIFEST.MF

**Comment by sprigogin** [comment]
CDT 9.0 has been released. When will GoEclipse support it?

-sergey

**Comment by bruno-medeiros** [comment]
Already supports it, in master: https://github.com/GoClipse/goclipse/blob/master/documentation/ChangeLog.md Release will come next week, probably.  I'm on holidays now ☀ ☺
