### ISSUE TITLE
Autocomplete doesn't work when importing package with an alias

### ISSUE THREAD

**Issue by parhamdoustdar** [GoClipse/goclipse#183]
I have a file that begins like this:

```
package main

import (
	"flag"
	"fmt"
	machinery "github.com/RichardKnop/machinery/v1"
	// ...
)
```

Autocomplete works fine for `fmt` and `flag`, but not for `machinery`. I'm guessing it's because of the fact that I'm importing it with an alias?

Here is the link to the project on Github, in case you want to see the project layout and why I'm importing it like this:

https://github.com/RichardKnop/machinery

**Comment by bruno-medeiros** [comment]
That would be a limitation with https://github.com/nsf/gocode , you'll have to file a report there.
