### ISSUE TITLE
GOROOT is not defined

### ISSUE THREAD

**Issue by dicos** [GoClipse/goclipse#184]
Hi, i am installed golang into this paths:
$ echo $GOROOT 
/home/dmitry/go
$ echo $GOPATH 
/home/dmitry/web/go
$ echo $PATH 
/home/dmitry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dmitry/go/bin

I can compile my files from console.

I'm use Eclipse Version: Mars.1 Release (4.5.1). 
After open *.go file Eclipse says: "GOROOT is not defined" and not working autocomplete.

**Comment by bruno-medeiros** [comment]
Ah, you still need to specify the GOROOT in the Goclipse preferences, even though the environment variable is already defined. (Admittedly it seems a bit unnecessary)
