### ISSUE TITLE
Custom imports don't work in autocompletion

### ISSUE THREAD

**Issue by parhamdoustdar** [GoClipse/goclipse#186]
I have an import like this:

```
import (
    machinery "github.com/RichardKnop/machinery/v1"
	"hamrah7.com/iwr/serverctl"
)
```

However, when I type `machinery.` and then press ctrl+space, Goclipse does not bring up a list of exported values from the `machinery` package.

Thanks for doing such an awesome job with the IDE, BTW!

**Comment by bruno-medeiros** [comment]
Custom imports like such is working on my machine. Note that you need to build the packages first for gocode to pick the completion for such packages. See if that's the issue.

**Comment by bruno-medeiros** [comment]
likely invalid
