### ISSUE TITLE
Show compile failures for test files

### ISSUE THREAD

**Issue by wolfgangmeyers** [GoClipse/goclipse#187]
Currently the IDE does not show compiler errors for test files on save. When compiler errors are present, the code completion often stops working after the point of the error but there is no clear indication of what the issue is. I believe the compiler doesn't actually compile test files until "go test" is invoked - maybe when editing test files, the goclipse editor could run this in the background on save?

**Comment by bruno-medeiros** [comment]
With the new version, no build of any kind is performed on save (neither normal, nor tests). You have to manually invoke the build using "Build Project" or "Build All" commands. But this is a separate issue. 

Regarding tests: By default, when a build is invoked, it doesn't build the tests files. You can enable that by selecting the #build-tests target and check the option to enable on workspace builds
![untitled2](https://cloud.githubusercontent.com/assets/4324232/13112585/3fb72058-d583-11e5-9120-70737a378b5c.png)
You can also enable *running* the tests during a build operation.

**Comment by wolfgangmeyers** [comment]
just updated goclipse, and this worked perfectly. Thanks!
