### ISSUE TITLE
Missing imports are not detected

### ISSUE THREAD

**Issue by wolfgangmeyers** [GoClipse/goclipse#189]
I was able to work around this by enabling the go project builder for auto builds, but with the default configuration, the editor does not show any errors when referencing missing imports.

**Comment by bruno-medeiros** [comment]
What is the output in the Go build console?

**Comment by bruno-medeiros** [comment]
If the errors show up in the Go build console, but they don't show up as problem markers in the Eclipse workspace and editor, and the Go project is inside the GOPATH, then that's a bug that was discovered very recently.

**Comment by wolfgangmeyers** [comment]
I started seeing this after updating goclipse.
When I disable the go builder on autobuild, I see no output from the build console when removing imports. The build console only has output when I have the go builder enabled for autobuilds. (unless I do a manual build, and then I do see output).

**Comment by bruno-medeiros** [comment]
I'm not sure I understand what the problem is then. If you remove the Go builder from autobuilder, then it will never get invoked (and therefore no build console output), except when you do a manual build.

**Comment by wolfgangmeyers** [comment]
Got it. When I upgraded this was disabled by default. Having it enabled on autobuild is more like the behavior I expected.
