### ISSUE TITLE
Can't use imported packages

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#19]
Reported by milak.mlk, Apr 16, 2013
What steps will reproduce the problem?
1. type go get <external package> (here github.com/robertkrimen/otto)
2. create a project which imports this newly imported package
3. can't compile in eclipse : 'import "github.com/robertkrimen/otto": cannot find package'
4. compile in command line 'go build <myprog.go>' : success...

What is the expected output? What do you see instead?
My program should compile

What version of the product are you using? On what operating system?
 - Having latest goclipse release
 - Eclipse-juno
 - Running on windows 7 with go 1.0.3

Please provide any additional information below.
 - maybe i missed something but i tried to restart many times, change gopath, etc.
 - i can see my newly imported package in my project gopath link (you know the link in the project)

Thanks

**Comment by bruno-medeiros** [comment]
outdated/invalid
