### ISSUE TITLE
How to cross compile ?

### ISSUE THREAD

**Issue by lukexue** [GoClipse/goclipse#191]
Oh no~~
Removed GOOS and GOARCH from preferences, they no longer have an apparent use.

But, how to cross compile ?

**Comment by bruno-medeiros** [comment]
Oh crap, I forgot about that use case. :weary: I'll see about adding it again. 
In the meanwhile, you can add a Program external tool builder (this one allows configuring environment variables) to a project's list of builders, in project properties . However, you won't get build error markers from that kind of build.

**Comment by lukexue** [comment]
thanks .
In the meanwhile, I will try to add external tool builder for cross compile

**Comment by dave-leblanc** [comment]
BIG +1 on this I've been using the cross compile feature for sometime only to find today that my binaries are broken. I would really love to have this feature back.

**Comment by nigelcook** [comment]
+1 on this as well. spent a couple of hours trying to figure out how to specify GOOS and GOARCH

**Comment by bruno-medeiros** [comment]
already working on it!
