### ISSUE TITLE
Executable file  doesnt exist.

### ISSUE THREAD

**Issue by zhanyuerong** [GoClipse/goclipse#197]
hi, I have the same problem with #188 .
my environment:
go 1.6
os windows 10
eclipse 4.5.2
goclipse 0.14.1

![image](https://cloud.githubusercontent.com/assets/2187964/14350878/970dd926-fcfe-11e5-9cab-ad0f9c22fe74.png)

Thank you for your help.

**Comment by bruno-medeiros** [comment]
What's the output of the build console?

**Comment by zhanyuerong** [comment]
![image](https://cloud.githubusercontent.com/assets/2187964/14371308/d8532868-fd68-11e5-9361-b0389162f006.png)

I use goclipse's default config.
I find hello.exe in D:\Go\bin, but this is go's installation directory, not my project directory.
thanks.

**Comment by bruno-medeiros** [comment]
What happens if you set GOPATH to the value above `E:\GoPackage;E:\workspace-go\GoProject` , and then run `go install hello` from the command line?

**Comment by zhanyuerong** [comment]
I find the problem , It really  golang problem.
According to your method, I set GOPATH and then run go install, the result is shown belown.
![image](https://cloud.githubusercontent.com/assets/2187964/14420655/dc207998-ffff-11e5-947e-24134aa62eea.png)

I still found hello.exe in D:\Go\bin, but when I removed GOBIN,  hello.exe was found in E:\workspace-go\GoProject\bin. Then  I use goclipse, the project works fine.
![image](https://cloud.githubusercontent.com/assets/2187964/14420939/666a8fa2-0001-11e6-9184-4c44080b8509.png)

I query this problem from google, get information:
**"[If the GOBIN environment variable is set, commands are installed to the directory it names instead of DIR/bin(DIR is a directory listed in the GOPATH). GOBIN must be an absolute path.](https://golang.org/cmd/go/)"**

I'm beginner in go.
Thank you for your help.

**Comment by bruno-medeiros** [comment]
Thanks for investigating this @zhanyuerong , I actually didn't know about GOBIN either.

**Comment by antman1p** [comment]
This does not work for me.  I am still getting no executable in my project bin or anywhere else for that matter.

**Comment by DukeDeng** [comment]
This does not work for me. I am still getting no executable in my project bin or anywhere else for that matter.
![image](https://cloud.githubusercontent.com/assets/18650165/23861662/abba63aa-0845-11e7-947b-4d5c90d3b8ac.png)
![image](https://cloud.githubusercontent.com/assets/18650165/23861692/c57ffa7a-0845-11e7-8c7b-09217f1710a4.png)

**Comment by DukeDeng** [comment]
I'm not able to generate "hello.exe" file on the local disk C .

**Comment by bruno-medeiros** [comment]
@DukeDeng  Have you check in `C:\goPath\bin` ?

**Comment by ganeshcece** [comment]
I managed to find the issue, It is no configuration issue or anything. You have to do 3 things as follows, 

1) Make sure GOPATH value is different from GOROOT.
2) Make sure GOBIN value is empty.
3) Your package name on the go file in eclipse should be main and not the package name "hello". To do this, File->New go file->Source file type should be -> Command source file-> Empty main function. Then type your code after which you can build to see the the .exe file in GOPATH/bin and the program run.

Worked for me.
