### ISSUE TITLE
Installation Software Has Encountered a Problem - Version: Mars.2 Release (4.5.2) Build id: 20160218-0600

### ISSUE THREAD

**Issue by Yeremilla** [GoClipse/goclipse#198]
Efforts to install goclipse using both github and local repository results in this error: "Installation Software Has Encountered a Problem".

The log is pasted below:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.cpp, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.googlecode.goclipse.core,0.14.1.v201602251806
No repository found containing: osgi.bundle,com.googlecode.goclipse.debug,0.14.1.v201602251806
No repository found containing: osgi.bundle,com.googlecode.goclipse.jvmcheck,1.0.0.v201602251806
No repository found containing: osgi.bundle,com.googlecode.goclipse.tooling,0.14.1.v201602251806
No repository found containing: osgi.bundle,com.googlecode.goclipse.ui,0.14.1.v201602251806
No repository found containing: org.eclipse.update.feature,goclipse_feature,0.14.1.v201602251806
No repository found containing: osgi.bundle,org.json,1.0.0.v201011060100

How can I get around this error? Help, anyone?

**Comment by bruno-medeiros** [comment]
So even if you download https://github.com/GoClipse/goclipse.github.io/archive/master.zip , and use that as a local repository, it doesn't work? That's very strange. Try removing all other Goclipse Software Sites before attempting installation, see if that helps.

**Comment by bruno-medeiros** [comment]
Closing as invalid/cant-reproduce. This is problem Github website caching taking some time to update to new Relase Site updates.
