### ISSUE TITLE
Let Go projects be created in arbitrary directories

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#20]
Reported by kyrieuon, May 11, 2013
Currently one can create a new Go project only in the current workspace, or from an already existing project.

As a workaround one has to create a new project in the current workspace, delete it, move the created directory structure to the desired location, and re-create the project from the moved directory.

See the "New Java Project" dialog as an example of a more functional project creation dialog.

**Comment by bruno-medeiros** [comment]
This has been fixed in master (0.10.0)
