### ISSUE TITLE
Syntax highlight is not work in goeclipse

### ISSUE THREAD

**Issue by phenrigomes** [GoClipse/goclipse#201]
If I write fmt.PrintXXX() - the syntax highlight not work. I installed the tools but nothing. Help?

**Comment by bruno-medeiros** [comment]
Can you attached a screenshot please? And what Goclipse version you have installed?

**Comment by phenrigomes** [comment]
Goclipse 0.14.1

Steps: 1) I compiled with fmt.PritXXSXA("") the error was undefined
fmt.PrintXXSXA, but only after compilation. 2) I changed to
fmt.PritSXA(""), the error was undefined fmt.PrintXXSXA and not undefined
fmt.PrintSXA. When I compile the error is changed.

2016-05-17 9:34 GMT-03:00 Bruno Medeiros <notifications@github.com>:

**Comment by bruno-medeiros** [comment]
I don't understand what is the problem you are having. Syntax highlighting is about coloring the source editor for different keywords, numbers, etc. 
It has nothing to do with compilation errors, that's a different thing.

**Comment by phenrigomes** [comment]
In Java programming if I type one method of class that is undefined the
editor shows me one error before compilation time. In goclipse is not the
same?

2016-05-18 9:23 GMT-03:00 Bruno Medeiros <notifications@github.com>:

**Comment by bruno-medeiros** [comment]
No, it's not like Java. It would be nice if it was, but that's not supported. Instead, you have to request a build manually for the project to be compiled, and errors to be shown. (although you can configure the build to happen when an editor is saved)

**Comment by phenrigomes** [comment]
How I use it?

2016-05-18 10:03 GMT-03:00 Bruno Medeiros <notifications@github.com>:
