### ISSUE TITLE
The env variables is not working

### ISSUE THREAD

**Issue by lukexue** [GoClipse/goclipse#205]
[
<img width="1280" alt="2016-05-31 1 17 38" src="https://cloud.githubusercontent.com/assets/2391716/15655266/1257ee5c-26ce-11e6-82be-e39929b54748.png">
](url)

**Comment by bruno-medeiros** [comment]
What do you mean, what is the problem? Are the environment variables not being passed to the build command?

**Comment by lukexue** [comment]
yes; 
no any effect when build project

**Comment by bruno-medeiros** [comment]
I've tried and it's working for me. Do you have `env` in OSX, or some other command to print the environment? Modify the Build Target to call the `env` command, to see what environment is being supplied.

**Comment by lukexue** [comment]
yes, it work.
it is another problem.
i am sorry about that . .

**Comment by bruno-medeiros** [comment]
no worries
