### ISSUE TITLE
Feature request: set source directories

### ISSUE THREAD

**Issue by MrCreosote** [GoClipse/goclipse#207]
I'm a complete Go newb working on a Go project hosted on github that doesn't use a src directory, but rather the effective source directory is the root of the repo. AFAICT, there's no way to get all the nice GoClipse features working without the code living in a src directory, and I definitely won't be able to get away with completely redoing another group's folder hierarchy. Hence, the ability to set source folders (like PyDev, for instance) would make GoClipse useable for this project (which I would really like). 

Thanks very much for your consideration.

**Comment by bruno-medeiros** [comment]
The requirement to have a `src` folder is requirement from the Go toolchain itself, not GoClipse. See this document for more info on Go project structure: https://golang.org/doc/code.html

You will need to create such a Go workspace with a `src` folder, and then clone the github project into there (Alternatively `go get` can be used). You then need to configure your GOPATH to point to that Go workspace folder (the one that has the `src` dir). Then in GoClipse you use the New Project Wizard to create a new Eclipse project with a custom location set to the existing github project directory (for example: `<GOWORKSPACE>/src/github.com/golang/example/`).

**Comment by MrCreosote** [comment]
I see, thanks for the education and being patient with a newbie question.
