### ISSUE TITLE
Invalid gocode completion result line: 

### ISSUE THREAD

**Issue by maxandersen** [GoClipse/goclipse#210]
I installed latest GoEclipse, latest Go and manually configured all the preferences
and in the end I just get:

```
Invalid gocode completion result line: 
```
as warning in error.

**Comment by bruno-medeiros** [comment]
What is the output of the Go Tools console after that?

**Comment by maxandersen** [comment]
I unfortunately cannot reproduce this again - after manually installing everything again it worked.

As I recall nothing actually showed up in in Go tools console, but I cannot verify it.

**Comment by bruno-medeiros** [comment]
I was able to replicate this with completion on "fmt.Println". It's just a false positive, a line with only whitespace.
