### ISSUE TITLE
Goclipse is not compatible with the latest CDT

### ISSUE THREAD

**Issue by ricardopadilha** [GoClipse/goclipse#212]
While trying to install the latest goclipse from either the Eclipse Marketplace (https://marketplace.eclipse.org/content/goclipse) or the update site (http://goclipse.github.io/releases/), I get asked to uninstall CDT 9.0.0 and install CDT 8.8. This is on Eclipse Neon 4.6.0.

Is there any specific reason for restricting the compatibility like that? Is there something one can do to help making goclipse compatible with Neon?

**Comment by bruno-medeiros** [comment]
It's already compatible in master: https://github.com/GoClipse/goclipse/blob/master/documentation/ChangeLog.md#nextversion
New release to come soon
