### ISSUE TITLE
Auto running gofmt does not work

### ISSUE THREAD

**Issue by refaelsh** [GoClipse/goclipse#237]
Go to Windows-->Preferences-->Go-->Tools and the check the "Format automatically on editor save".
Well, this check box has no effect. This feature simply does not work.
I am obviously missing something. I require help :-)

**Comment by bruno-medeiros** [comment]
What does the Go Tools Log console say after you save a file? (look in the Console view for this console)

**Comment by refaelsh** [comment]
@bruno-medeiros I am sorry, but I don't understand where to look. Can You please explain with more details?

**Comment by bruno-medeiros** [comment]
![image](https://cloud.githubusercontent.com/assets/4324232/23079511/1c1e0eb2-f545-11e6-8d2a-f8a11c7428ea.png)

The Eclipse "Console" view has different console panes, one of them being "Go Tools Log". There's a dropdown menu to select the one of the different panes.

**Comment by refaelsh** [comment]
Thank You very much for Your patient answer :-)
I have no such option in that drop down menu.
Here is a screenshot: https://www.dropbox.com/s/v9naxz48ck2f4ai/Screenshot_2017-02-18_21-36-45.png?dl=0

**Comment by bruno-medeiros** [comment]
(See "Help / Installed Software" menu)

**Comment by bruno-medeiros** [comment]
(See "Help / Installation Details" menu option)

**Comment by refaelsh** [comment]
I have version 0.16.1, here is a screenshot:
https://www.dropbox.com/s/z7xvo9foe016f6w/Screenshot_2017-02-20_12-16-40.png?dl=0

**Comment by bruno-medeiros** [comment]
That's weird. In any case the editor you are opening the .go file is not Goclipse's editor. The icon is wrong, and also the Outline view is different. This is how it should look like:

**Comment by bruno-medeiros** [comment]
That's weird. In any case the editor you are opening the Go file is not Goclipse's editor. The icon is wrong, and also the Outline view is different. This is how it should look like:
![image](https://cloud.githubusercontent.com/assets/4324232/23121492/82663ac2-f758-11e6-9c15-2158f7e8b577.png)
Try, right clicking on .go file, and do "Open With / Go Editor", like show above.

**Comment by refaelsh** [comment]
Thanks. It works now. The file was open with "Liclipse Go Editor", it was the default double click action, that what confused Me. As soon as I opened it with "Go Editor", everything started working.
Thanks! :-)

**Comment by bruno-medeiros** [comment]
Ah, Liclipse, that explains... I was wondering which editor it could be since, I didn't know of any other Go editors/IDEs for Eclipse
