### ISSUE TITLE
Conform to naming standards

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#3]
Currently the primary plugin is called goclipse.  To conform to eclipse community naming standards, it should be something like com.googlecode.goclipse

Additionally, the feature currently displays "goclipse_feature" as its name during installation.  It should probably display something more human-friendly like "Goclipse Feature"

#1 devoncarew
"I changed the feature label to "GoClipse" (from "goclipse_feature"). I also added a category for the update site so that the feature wouldn't appear in the uncategorized group.

I agree re: renaming the plugin id. Maybe something like org.goclipse.ui or org.goclipse.ide? Anyway, something a bit longer then just goclipse. Renaming a plugin in Eclipse is problematic however. I suspect users will have to uninstall the old version of the feature before they install the new one. Not something that we should do without general agreement and some planning around the timing of it."

**Comment by bruno-medeiros** [comment]
this has mostly been done, the plugin names have been cleaned up.
