### ISSUE TITLE
UTF-8 chinese character GoCode

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#31]
What steps will reproduce the problem?
1. see this discussion : https://github.com/nsf/gocode/issues/159#issuecomment-24826213

2. the code:
package main

import (
    "fmt"
)

func main() {
    fmt.Printf("")    // work
    //世界
    fmt.Printf("")    // work
    //體
    fmt.  // need one more english character to trigger the right list
    //體體體體
    fmt. // broken, if the chinese character above display more than one time
}

What is the expected output? What do you see instead?
Expected: the member function
Instead: all the problem situation is above.

What version of the product are you using? On what operating system?
Eclipse: Build id: 20130225-0426 (Juno)
Golipse: 0.7.6v439
Gocode: Newest Version ( Today )
Go: go1.1

Please provide any additional information below.
As the discussion in GoCode's GitHub issue, 
some chinese character is decoded in wrong way.
Can it be fixed ?

**Comment by bruno-medeiros** [comment]
Can't reproduce, reckon this was a gocode issue
