### ISSUE TITLE
Debugger Should not Stop in Runtime Files by Default

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#40]
Platform: Linux (Ubuntu 13.10)
Arch:       amd64
Go:          go version devel +e5646e0df5a5 Thu Feb 13 19:59:09 2014 -0500 linux/amd64

By default, the CDT debugger used by GoClipse will pause in runtime files compiled into the application.  For example, before hitting main on an application it will stop in rt0_linux_amd64.s.

It would be desirable for this to be optional and configurable.

**Comment by bruno-medeiros** [comment]
Oh, this has already been fixed
