### ISSUE TITLE
Improve Tokenizer (Ragel?)

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#6]
What steps will reproduce the problem?

Have import parser parse a source file containing lines like:

  fmt.Printf(" <import path=")
  fmt.Printf(" ")

What is the expected output? What do you see instead?

  Should not create an import entry, but does:

  )fmt.Printf(

**Comment by bruno-medeiros** [comment]
Fixed in master, using a new outline page which uses `oracle describe`, and not the builting parser which has bugs like these.
