### ISSUE TITLE
More syntax highlighting options

### ISSUE THREAD

**Issue by baconalot** [GoClipse/goclipse#65]
I would love to have more syntax highlighting options. 
Especially:

-function declaration names
-type declaration names
-variable names

I understand that these are harder than just keyword because they include introspecting the source, but readability would be greatly increased.

**Comment by bruno-medeiros** [comment]
I've Added two new syntax highlighting options: Operators, and Syntax Control Characters (braces, parentheses, semicolon, etc.).

Highlighting of semantic elements remains more difficult, I don't think I will have time to work on that.

**Comment by bruno-medeiros** [comment]
I've created a new issue for Semantic highlighting: #111
