### ISSUE TITLE
GoCode Lib Path

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#8]
What steps will reproduce the problem?
1.Editing any go source file with gocode daemon running.

I use gocode autocompletion for both the standard go libraries and the appengine's go libraries with the aid of the lib-path option of gocode. 

But I noticed goclipse sets it to the project directory. This works well for standard go libraries, but it prevents autocompletion of appengine's libraries.

I will suggest if goclipse can append the project directory to gocode's lib-path instead of replacing it.

What version of the product are you using? On what operating system?
Ubuntu 11.04 32 bit goclipse 0.0.26
Jun 30, 2011 Delete comment #1 emerson.steel
The problem is known.  That solution won't work for multiple projects.  The correct solution is to add the ability to add external libraries/projects to the project properties.  This is larger, however, because it affects the build system as well.

The work around I used is copying the appengine package into my Go/pkg directory.  This is not ideal, but gets past the problem until a proper solution is worked. 
Status: Accepted 

Jun 30, 2011 comment abiola89
I tried that already by putting a symlink of appengine package in $GOROOT/pkg/$GOOS_GOARCH but i forgot the appengine package itself is not in the folder which is why I created this issue in the first place. But now I've copied it too and it works for the main time.

Thanks.
Jul 2, 2011 comment  emerson.steel
Also remember that App Engine comes with the proper Go environment prebuilt for your platform.  So, the compiler is the same as the version used when you upload to the cloud.  You can point goclipse at the appengine go root directory and you'll avoid library mismatches.

Sep 23, 2011 comment  Marek.Zawirski
This is also an issue for projects using custom build system. In my setup both sources and output files are out of Eclipse project directory, so I cannot configure auto-completion accordingly other than by using symlink hack. External library support would probably solve the problem. 
Other than that, how about binary setting "Append project's directory to gocode lib-path" vs "Overwrite gocode lib-path with project's directory" ?

May 2, 2013 comment  james.pirruccello
On OS X Eclipse Juno SR2 with GoClypse v0.7.6, this continues to be a problem. I think commenter #4, Marek, has a good summary. GoClypse rewrites ~/.config/gocode/config.json's lib-path rather than appending, and it does not permit the specification by the user of out-of-project paths to use as the lib-path.

**Comment by bruno-medeiros** [comment]
I believe this has now been fixed as Goclipse appends to the Goclipse global GOPATH the project's entry to lib-path. It still rewrites  '~/.config/gocode/config.json' but any previous gocode lib-path entries can be added to the Goclipse global GOPATH.
