### ISSUE TITLE
Go Project Builder options

### ISSUE THREAD

**Issue by dmuntean** [GoClipse/goclipse#81]
Currently Go Project Builder assumes there is just 1 file per go package, which is a problem when you have your package split across many files.

The current way builder invokes "go build" is:
/usr/local/go/bin/go build -o /home/user/workspace/project/bin/myfile myfile.go

The way it should be invoked is:
/usr/local/go/bin/go build -o /home/user/workspace/project/bin/myfile /home/user/workspace/project/src

Same applies to error highlighting - goclipse is highlighting "errors" for missing definitions, which are defined in other files, but under same package name.

**Comment by bruno-medeiros** [comment]
I believe this is invalid as of Goclipse 0.9.1, as it is now using `./...` pattern to build files
