### ISSUE TITLE
Should attempt to terminate currently running program before running program again?

### ISSUE THREAD

**Issue by sesteel** [GoClipse/goclipse#9]
Reported by kardianos, Aug 7, 2011
What steps will reproduce the problem?
1. main() { http.ListenAndServe(...) }
2. Start Program
3. Make changes
4. Forget to hit the stop button
4  Start Program

What is the expected output? What do you see instead?
I would like either the run to be disabled or for the program to terminate the existing program.  Rather the first program is forgotten and can no longer be controlled in eclipse (sh# killall main)

What version of the product are you using? On what operating system?

Please provide any additional information below.

Aug 9, 2011 comment  emerson.steel
This should be an option in the run configuration.  

Aug 13, 2011  comment  emerson.steel
This should also happen on Windows before a build because it locks the file and causes the build to fail.

IF ON WINDOWS AND BUILDING
  DISPLAY USER WARNING "Building requires the currently running process to shutdown.  Are you sure you want to do this?" [YES|NO]

**Comment by CarlSmotricz** [comment]
I think that this would go against the Eclipse philoosphy. In the Java perspective, you can run as many instances of your program as you like. The consoles for those runs are retrievable and you can kill them with the red button on the respective console. Even better, each running program can be accessed from the debugger, and threads or whole programs killed selectively. That's rather sweet, though I realize it may be some time before that kind of comfort comes to GoClipse.

**Comment by bruno-medeiros** [comment]
Issue reference in commit 35977e7 above is incorrect
