### ISSUE TITLE
Some weird `./...` in the compilation line

### ISSUE THREAD

**Issue by zerkms** [GoClipse/goclipse#96]
I have installed the go v1.3.3 and goclipse v0.9.1

Now when I try to build a project this is what appears in console

```
************  Building Go workspace  ************
------- Building Go project: hello-world  -------
>> Running: /usr/local/bin/go install -v -gcflags -N -l ./...
   with GOPATH: /home/zerkms/workspace/hello-world:/home/zerkms/go
warning: "./..." matched no packages
   ^^^ Terminated, exit code: 0 ^^^ 
************  Build terminated.  ************
```

The `./...` part looks suspicious and I cannot think of what may be wrong.

Any ideas?

**Comment by aceperry** [comment]
Got the same problem, bruno-medeiros' post didn't seem to help.  The console says, 'Build terminated'

Not sure how to get beyond that point.  Any help would be appreciated.  Thanks.

**Comment by bruno-medeiros** [comment]
I've added the following to the UserGuide:
"Goclipse will specify the `./...` pattern to `go build`, to match all Go packages in the project/GOPATH being built. **(note that .go files directly under src/ do not belong to any Go package and as such will not be built by this command)**. For more information see the command line help: `go help packages`. "

Basically, for the case above, you would need to have some .go file in /home/zerkms/workspace/hello-world/src/<some_sub_dir>

**Comment by bruno-medeiros** [comment]
I've added the following info to the UserGuide:
"Goclipse will specify the `./...` pattern to `go build`, to match all Go packages in the project/GOPATH being built. **(note that .go files directly under src/ do not belong to any Go package and as such will not be built by this command)**. For more information see the command line help: `go help packages`. "

Basically, for the case above, you would need to have some .go file in `/home/zerkms/workspace/hello-world/src/<some_sub_dir>`

**Comment by tt7** [comment]
After moving your codes from "src" to <some_sub_dir>, you also need to change the package name from "src" to "some_package" in each code file manually.

**Comment by bruno-medeiros** [comment]
> After moving your codes from "src" to , you also need to change the package name from "src" to "some_package" in each code file manually. 

Exactly, and that's the standard way how Go expects workspaces to be organized: https://golang.org/doc/code.html#Workspaces
