### ISSUE TITLE
Oracle enhancements

### ISSUE THREAD

**Issue by baconalot** [GoClipse/goclipse#99]
I really like the ctrl-lmbclick (open definition) integration with oracle, but I have the following enhancements (I can split them in multiple issues if you want):

A: When code is in error a popup with "Program exited with nonzero status:1" appears. I get that this cant be fixed because it is dependent on oracle. However clicking "ok" all the time is cumbersome and it would be nice if the error is just silently ignored and logged in console.

B: When a type is ctrl-clicked we get " selected name does not refer to a source element, rather its a ref to type xyz (size 40, align 8). Is there a compelling reason not to jump to the type? When I click  I just want to see the symbol. I don't care if it is a type or a declaration or whatever, I just want to see it.

C: When I click certain symbols I get a dropdown with "-Open definition -Open definition (goclipse oracle)" Is there a way to not show this and always do the oracle one, since the first one almost always errs?

**Comment by bruno-medeiros** [comment]
I've implemented A and C, but I'm not sure what you mean with case B. Case you give an example with source?

**Comment by bruno-medeiros** [comment]
I'm marking this as closed, please open a new issue for aspect B, if so desired (with more details)
